[package]
name = "reset_combo_pairing"
version = "0.1.0"
authors = ["Peter"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = "3.3.0"
crossterm = "0.18.2"
